### ISSUE TITLE
Feature-Request: Display Myth Rank Level from Myth Rank XP

### ISSUE THREAD

**Issue by somefunguy** [apocalyptech/ttwl-cli-saveedit#1]
Display current Myth Rank Level using Myth Rank XP as an input using one of these formulas (either should do the trick):
((((60*((40+1)^2.3)+12.33)+XP)-12.33)/60)^(1/2.3)-40
or
((((60*((40+1)^2.3)-60)+XP)+60)/60)^(1/2.3)-40
could potentially be a bit off due to precision issues, but should at least be close enough.

**Comment by apocalyptech** [comment]
Ah, forgot this was in here -- was taken care of a little while ago.  Thanks for the formulas, much appreciated!
